// SPDX-License-Identifier: GPL-3.0-or-later
// Arrocco UI — the CollectiCraft piece set. See pieces.h.
//
// Two bitmaps go down per piece. The MASK is painted white first: it is the silhouette
// grown by 2 px, and it is what stops a black piece from disappearing into a dithered
// dark square. The INK goes on top in black: for a black piece that is the filled
// silhouette, for a white piece only its contour, so the inside stays white.
//
// The bitmaps come from assets/pieces/piece_bitmaps.h, generated by
// assets/pieces/trace_reference.py. Redraw the pieces there, not here.
#include "arrocco/ui/pieces.h"

#include <Adafruit_GFX.h>

#include "arrocco/ui/layout.h"
#include "arrocco/ui/piece_bitmaps.h"

namespace arrocco::ui {

namespace {

static_assert(art::kPieceSize == kSquare, "the piece art is drawn for this square size");

struct Art {
  const uint8_t* mask;
  const uint8_t* white;
  const uint8_t* black;
};

Art artFor(chess::PieceType type) {
  using namespace art;
  switch (type) {
    case chess::PieceType::King:   return {kKMask, kKWhite, kKBlack};
    case chess::PieceType::Queen:  return {kQMask, kQWhite, kQBlack};
    case chess::PieceType::Rook:   return {kRMask, kRWhite, kRBlack};
    case chess::PieceType::Bishop: return {kBMask, kBWhite, kBBlack};
    case chess::PieceType::Knight: return {kNMask, kNWhite, kNBlack};
    default:                       return {kPMask, kPWhite, kPBlack};
  }
}

}  // namespace

// drawBitmap paints only the set bits, so the passes layer cleanly.

void drawPieceHalo(Adafruit_GFX& gfx, int16_t x, int16_t y, chess::Piece piece) {
  if (piece.isNone()) return;
  gfx.drawBitmap(x, y, artFor(piece.type()).mask, art::kPieceSize, art::kPieceSize, kWhite);
}

void drawPieceInk(Adafruit_GFX& gfx, int16_t x, int16_t y, chess::Piece piece) {
  if (piece.isNone()) return;
  const Art a = artFor(piece.type());
  const bool white = piece.color() == chess::Color::White;
  gfx.drawBitmap(x, y, white ? a.white : a.black, art::kPieceSize, art::kPieceSize, kBlack);
}

void drawPiece(Adafruit_GFX& gfx, int16_t x, int16_t y, chess::Piece piece) {
  drawPieceHalo(gfx, x, y, piece);
  drawPieceInk(gfx, x, y, piece);
}

}  // namespace arrocco::ui
