#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Turn a picture into the 800x480 1-bit sleep screen of Arrocco.

The default picture is Vincent van Gogh, "The Starry Night" (1889), public domain:
the Google Art Project scan on Wikimedia Commons, 1920 px wide version
https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1920px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg

ffmpeg scales it to the panel width, crops 480 rows between the moon and the village,
lifts the contrast and sharpens the brush strokes a little; Atkinson error diffusion then
makes it 1 bit. Atkinson drops a quarter of the error, which keeps the whites clean and
the strokes crisp on e-paper. Writes the C++ header for the firmware and a PNG preview.

Usage: python3 assets/sleep/make_sleep_art.py <picture.jpg> [crop_y]
"""
import os
import struct
import subprocess
import sys
import zlib

W, H = 800, 480
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
HEADER = os.path.join(REPO, "lib", "arrocco", "src", "arrocco", "ui", "sleep_art.h")
PREVIEW = os.path.join(HERE, "sleep_art_preview.png")
TONE = "eq=contrast=1.12:gamma=1.05,unsharp=5:5:0.7"
ATKINSON = [(1, 0), (2, 0), (-1, 1), (0, 1), (1, 1), (0, 2)]  # each gets 1/8 of the error


def gray(src, crop_y):
    vf = "scale=%d:-2:flags=lanczos,crop=%d:%d:0:%d,%s,format=gray" % (W, W, H, crop_y, TONE)
    raw = subprocess.run(["ffmpeg", "-v", "error", "-i", src, "-vf", vf, "-f", "rawvideo", "-"],
                         capture_output=True, check=True).stdout
    if len(raw) != W * H:
        raise SystemExit("ffmpeg gave %d bytes, expected %d (picture too short for this crop?)" % (len(raw), W * H))
    return [float(b) for b in raw]


def dither(px):
    ink = bytearray(W * H)  # 1 = ink (black)
    for y in range(H):
        for x in range(W):
            i = y * W + x
            old = px[i]
            white = old >= 128
            ink[i] = 0 if white else 1
            err = (old - (255.0 if white else 0.0)) / 8
            for dx, dy in ATKINSON:
                xx, yy = x + dx, y + dy
                if 0 <= xx < W and yy < H:
                    px[yy * W + xx] += err
    return ink


def write_header(ink, src_name):
    data = bytearray(W * H // 8)
    for i, bit in enumerate(ink):
        if bit:
            data[i >> 3] |= 0x80 >> (i & 7)
    rows = [", ".join("0x%02X" % b for b in data[j:j + 16]) for j in range(0, len(data), 16)]
    body = ",\n    ".join(rows)
    with open(HEADER, "w") as f:
        f.write("// SPDX-License-Identifier: GPL-3.0-or-later\n"
                "// Generated by assets/sleep/make_sleep_art.py - do not edit by hand.\n"
                "// The sleep screen: Vincent van Gogh, \"The Starry Night\" (1889), public domain\n"
                "// (Google Art Project scan, Wikimedia Commons; source file %s).\n"
                "// 800x480, 1 bit, row-major, MSB first, bit set = ink. inline: one copy in flash however\n"
                "// many files include it. Draw over paper with\n"
                "// drawBitmap(0, 0, kSleepArt, kSleepArtW, kSleepArtH, ink).\n"
                "#pragma once\n#include <cstdint>\n\nnamespace arrocco::ui::art {\n\n"
                "inline constexpr int kSleepArtW = %d;\ninline constexpr int kSleepArtH = %d;\n\n"
                "inline constexpr uint8_t kSleepArt[%d] = {\n    %s,\n};\n\n"
                "}  // namespace arrocco::ui::art\n" % (src_name, W, H, len(data), body))


def write_preview(ink):
    raw = b"".join(b"\x00" + bytes(0 if ink[y * W + x] else 255 for x in range(W)) for y in range(H))

    def chunk(tag, payload):
        c = tag + payload
        return struct.pack(">I", len(payload)) + c + struct.pack(">I", zlib.crc32(c))
    with open(PREVIEW, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", W, H, 8, 0, 0, 0, 0))
                + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b""))


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    src = sys.argv[1]
    crop_y = int(sys.argv[2]) if len(sys.argv) > 2 else 45
    ink = dither(gray(src, crop_y))
    write_header(ink, os.path.basename(src))
    write_preview(ink)
    print("wrote %s (%d bytes of bitmap) and %s" % (os.path.relpath(HEADER, REPO), W * H // 8,
                                                    os.path.relpath(PREVIEW, REPO)))


if __name__ == "__main__":
    main()
